# Generated by Django 6.0.1 on 2026-02-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.TextField(blank=True),
        ),
    ]
