# Generated by Django 6.0.1 on 2026-02-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_profile_followers_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.IntegerField(),
        ),
    ]
