# Generated by Django 6.0.1 on 2026-03-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0009_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
